In [8]:
import time

import torch

print(torch.__version__)

2.4.0


In [9]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


In [10]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


In [13]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.1889, -0.9927,  0.6024,  0.8554],
        [ 1.5902, -0.4340, -0.8543, -0.0814],
        [-0.2264, -0.5283, -0.4612,  0.3073]])


In [14]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [15]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [16]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [17]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

tensor([True, True, True, True])


In [18]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


In [19]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


In [20]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [21]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([20., 20., 20.])


In [22]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


In [23]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 0,  0,  0,  0,  0],
        [-1,  0,  0, -1,  0],
        [ 1,  0,  0,  0,  0],
        [-1,  2,  0, -1,  0],
        [ 0,  0,  0, -1,  0]])


In [24]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

tensor([[-0.9782, -0.0857],
        [-0.7515, -0.4308],
        [ 0.6386,  1.8052],
        [-0.1366, -0.7405],
        [ 0.1331,  0.7974],
        [ 0.3110, -0.6700]]) torch.Size([6, 2])
tensor([[-0.9782, -0.0857],
        [-0.7515, -0.4308],
        [ 0.6386,  1.8052],
        [-0.1366, -0.7405],
        [ 0.1331,  0.7974],
        [ 0.3110, -0.6700]]) torch.Size([6, 2])


In [25]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[ 0.7762,  0.7879],
         [-1.6049,  0.8044]],

        [[-0.4805, -0.6205],
         [ 1.6389,  0.8475]],

        [[ 0.6746,  0.1835],
         [ 0.8861,  0.8113]]]) torch.Size([3, 2, 2])


In [26]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


In [27]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


In [28]:
def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0143 sec.


In [29]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0031 sec.


In [30]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[ 1.3098, -0.5713,  0.0640],
        [-0.7508,  0.5204,  0.8731],
        [-1.5216, -1.1465, -2.2621]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[ 1,  0,  0],
        [ 0,  0,  0],
        [-1, -1, -2]])


In [31]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])
