In [1]:
import torch

In [2]:
# define linear model
model = torch.nn.Linear(10, 1)

In [4]:
# Create fake inputs and outputs
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=} {y=}')

x=tensor([[-5.6965e-01,  9.6438e-01, -3.4630e-01,  6.4887e-01, -7.1544e-02,
         -7.0036e-01,  5.4114e-01,  4.9935e-01, -1.7516e+00,  2.8906e-01],
        [ 2.8334e-01,  3.3752e-01, -6.9480e-01,  1.2078e+00, -3.2144e-01,
         -6.0109e-01, -4.1943e-01,  2.5843e-01,  1.2566e-01, -2.7729e+00],
        [-2.9198e-01, -2.6308e-01,  2.0695e+00, -2.0523e-01, -6.1803e-01,
         -6.6829e-01,  3.6443e-01, -3.6826e-02,  1.2324e+00, -1.2545e-03],
        [ 9.2405e-02,  1.6785e+00, -6.9764e-01, -1.4458e+00, -9.0353e-01,
          1.9934e+00,  2.0998e-01,  4.6773e-01,  1.9550e-01, -1.6810e+00],
        [-8.0212e-01, -5.5048e-01,  4.0956e-01, -2.0166e-01,  1.5393e+00,
          1.5641e+00,  7.9732e-01, -9.1312e-01,  6.2609e-01, -7.0846e-01],
        [ 6.7342e-01,  4.3496e-01, -3.4339e-01,  1.1129e-01, -8.2448e-01,
          1.3478e-01, -7.7379e-01,  1.3177e+00,  5.4951e-01,  1.3035e+00],
        [-6.1648e-01, -1.3671e-01, -2.3454e-01, -4.7073e-02,  9.2930e-01,
         -4.2690e-01, -2.8138e

In [6]:
# prediction
pred_y = model(x)
print(pred_y)

tensor([[ 0.6655],
        [ 0.0762],
        [-0.4832],
        [-0.0106],
        [-1.1581],
        [ 1.0625],
        [-0.4928],
        [ 0.5843],
        [ 0.2211],
        [ 0.1339],
        [ 0.1773],
        [ 1.1826],
        [ 0.5905],
        [-0.8727],
        [ 1.2234],
        [ 0.8343],
        [ 0.4573],
        [-0.2076],
        [-0.0214],
        [-0.9934]], grad_fn=<AddmmBackward0>)


In [8]:
# now we need to compare the expected output with the predicted output
# Use the l2 loss in regression
# here we are using the built-in mse-loss function
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(1.3622, grad_fn=<MseLossBackward0>)


In [9]:
# Writing the loss function ourselves
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
  
mse_loss(pred_y, y)

tensor(1.3622, grad_fn=<MeanBackward0>)

In [10]:
# Binary classification
# values are random numbers and check if they are greater than 0
# we then convert the boolean to float which will give either a 0 or 1
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]])


In [13]:
# loss function for binary classification
# binary cross entropy with logits will add the sigmoid for us
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.6163, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [44]:
# Multi-class classification
n_classes = 3
model = torch.nn.Linear(10, n_classes)

y = torch.zeros(20).long()

# for every class, we add a random number to y and check if it is greater than 0
# This will allow us to have a multi-class classification
# The values need to be integers because the loss function for multi-class
# classification expects integers
for i in range(n_classes - 1):
  y += (torch.randn(20) > 0).long()
print(y)

tensor([1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 1])


In [46]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

tensor(1.0637, grad_fn=<NllLossBackward0>)
